services:
  app1: &app
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app1
    networks:
      - backend
      - payment-processor
    environment:
      - MIX_ENV=prod
      - RELEASE_COOKIE=secret_cookie
      - RELEASE_NODE=api1@app1
      - PEER_NODES=api2@app2
      - PORT=9999
      - SECRET_KEY_BASE=j/s16IqcuOkGYYwGZBPTZc9clvsn7ZDeg3w+/EGAHUzDZa+VxEma/TGKMXfLXIZ2
      - PROCESSOR_DEFAULT_URL=http://payment-processor-default:8080
      - PROCESSOR_FALLBACK_URL=http://payment-processor-fallback:8080
    deploy:
      resources:
        limits:
          cpus: "0.80"
          memory: "170M"

  app2:
    <<: *app
    container_name: app2
    environment:
      - MIX_ENV=prod
      - RELEASE_COOKIE=secret_cookie
      - RELEASE_NODE=api2@app2
      - PEER_NODES=api1@app1
      - PORT=9999
      - SECRET_KEY_BASE=j/s16IqcuOkGYYwGZBPTZc9clvsn7ZDeg3w+/EGAHUzDZa+VxEma/TGKMXfLXIZ2
      - PROCESSOR_DEFAULT_URL=http://payment-processor-default:8080
      - PROCESSOR_FALLBACK_URL=http://payment-processor-fallback:8080
    deploy:
      resources:
        limits:
          cpus: "0.60"
          memory: "170M"

  nginx:
    image: nginx:1.29.0-alpine 
    container_name: backend-fight-nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 9999:9999
    depends_on:
      - app1
      - app2
    networks:
      - backend
    deploy:
      resources:
        limits:
          cpus: '0.10'
          memory: '10MB'

networks:
  backend:
  payment-processor:
    external: true
